### ISSUE TITLE
what is expected to be provided as key

### ISSUE THREAD

**Issue by alperyilmaz** [msoute/gnome3-aws-extension#2]
Hi, 
first of thanks for such valuable tool. the extension works fine and can list the instances. but I'm having trouble with connecting.
normally this is how I connect:

```bash
ssh -i keypair.pem ec2-user@some-ip.region.compute.amazonaws.com
```

In README, you already mentioned that "SSH Key usage is not implemented yet. Public key authentication only works with the default key." But how do I define a default key? In my aws config file only entries are:

```
[default]
region = us-west-2
aws_secret_access_key = ***
aws_access_key_id = ***
```
I'd be glad if you can guide me about the *default key* issue..

Thanks..

**Comment by msoute** [comment]
ssh defaults to ~/.ssh/id_*.pub. 

I've just uploaded a new version that implements this feature, please try it !
