### ISSUE TITLE
Empty Server List

### ISSUE THREAD

**Issue by kevin-fries** [msoute/gnome3-aws-extension#3]
When I run this extension, the icon appears at the top of my screen, but clicking on it produces a blank list.  If I run 'aws ec2 describe-instances', I get a list of machines.  I tried to click on config, but there is no save button, and I am not sure it is taking the configuration items, as when I run this configuration again, all the fields are again blank.

I am lost as to what to do next.

**Comment by msoute** [comment]
Hi,

Did you configure an Aws Tag Filter Value ?

**Comment by kevin-fries** [comment]
Yes, but I don't think my settings are getting saved, everything on the dialog box is grey's out.

**Comment by msoute** [comment]
What version of Gnome are you running ?
What version of the extension do you have installed ?
And do you have the aws cli installed ?
